#!/bin/bash
############################
# .make.sh
# This script creates symlinks from the home directory to any desired dotfiles in ~/dotfiles
############################

########## Variables

dir=~/dotfiles                    # dotfiles directory
olddir=~/dotfiles_old             # old dotfiles backup directory
files="gitconfig gitignore_global zshrc mongorc.js"    # list of files/folders to symlink in homedir
binfiles="git-branch-delete git-live-log"

##########

# create dotfiles_old in homedir
echo "Creating $olddir for backup of any existing dotfiles in ~"
mkdir -p $olddir
echo "...done"

# change to the dotfiles directory
echo "Changing to the $dir directory"
cd $dir
echo "...done"

# move any existing dotfiles in homedir to dotfiles_old directory, then create symlinks
for file in $files; do
    echo "Moving any existing dotfiles from ~ to $olddir"
    mv -f ~/.$file ~/dotfiles_old/
    echo "Copying $file to home directory."
    cp -Rf $dir/$file ~/.$file
done

for file in $binfiles; do
    echo "Creating symlinks for bin files"
    sudo  ln -sf $dir/bin/$file /usr/bin/$file
    echo "Done symlinks"
done

#add to git config the global ignores
git config --global core.excludesfile ~/.gitignore_global
